# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /h/bholen01/EE26/project_1/project_1.cache/wt [current_project]
set_property parent.project_path /h/bholen01/EE26/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files /h/bholen01/EE26/butterfly_unit/rominit_butterfly.coe
read_vhdl -library xil_defaultlib {
  /h/bholen01/EE26/project_1/project_1.srcs/sources_1/new/complex.vhd
  /h/bholen01/EE26/project_1/project_1.srcs/sources_1/new/butterfly_unit.vhd
  /h/bholen01/EE26/project_1/project_1.srcs/sources_1/new/fft_8point_3stage.vhd
  /h/bholen01/EE26/project_1/project_1.srcs/sources_1/new/fft_wrapper.vhd
}
read_xdc /h/bholen01/EE26/project_1/project_1.srcs/constrs_1/new/pinout.xdc
set_property used_in_implementation false [get_files /h/bholen01/EE26/project_1/project_1.srcs/constrs_1/new/pinout.xdc]

synth_design -top fft_wrapper -part xc7a100tcsg324-1
write_checkpoint -noxdef fft_wrapper.dcp
catch { report_utilization -file fft_wrapper_utilization_synth.rpt -pb fft_wrapper_utilization_synth.pb }
