# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir Z:/EE26/floatin_point_multiplier/floatin_point_multiplier.cache/wt [current_project]
set_property parent.project_path Z:/EE26/floatin_point_multiplier/floatin_point_multiplier.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo z:/EE26/floatin_point_multiplier/floatin_point_multiplier.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files z:/EE26/floatin_point_multiplier/rominit.coe
read_vhdl -library xil_defaultlib {
  Z:/EE26/project_1_v2/project_1_v2.srcs/sources_1/new/adder.vhd
  Z:/EE26/floatin_point_multiplier/floatin_point_multiplier.srcs/sources_1/new/array_multiplier.vhd
  Z:/EE26/floatin_point_multiplier/floatin_point_multiplier.srcs/sources_1/new/floating_point_multiplier.vhd
  Z:/EE26/floatin_point_multiplier/floatin_point_multiplier.srcs/sources_1/new/summation_unit.vhd
  Z:/EE26/floatin_point_multiplier/floatin_point_multiplier.srcs/sources_1/new/hardware_interface.vhd
}
read_ip -quiet z:/EE26/floatin_point_multiplier/floatin_point_multiplier.srcs/sources_1/ip/dist_mem_gen_0_1/dist_mem_gen_0.xci
set_property used_in_implementation false [get_files -all z:/EE26/floatin_point_multiplier/floatin_point_multiplier.srcs/sources_1/ip/dist_mem_gen_0_1/dist_mem_gen_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc Z:/EE26/floatin_point_multiplier/floatin_point_multiplier.srcs/constrs_1/new/pinout.xdc
set_property used_in_implementation false [get_files Z:/EE26/floatin_point_multiplier/floatin_point_multiplier.srcs/constrs_1/new/pinout.xdc]


synth_design -top hardware_interface -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef hardware_interface.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file hardware_interface_utilization_synth.rpt -pb hardware_interface_utilization_synth.pb"
