webtalk_init -webtalk_dir Z:/EE26/floatin_point_multiplier/floatin_point_multiplier.sim/sim_1/behav/xsim/xsim.dir/interface_test_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Mar  5 19:04:45 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "5e9c8e46-8b44-48d8-9140-8d2aa204e78a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "74decd8987844eb8ae1e39eac47d7f05" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "12" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3696 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "9" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.86_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "13828_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3137204936 -regid "" -xml Z:/EE26/floatin_point_multiplier/floatin_point_multiplier.sim/sim_1/behav/xsim/xsim.dir/interface_test_behav/webtalk/usage_statistics_ext_xsim.xml -html Z:/EE26/floatin_point_multiplier/floatin_point_multiplier.sim/sim_1/behav/xsim/xsim.dir/interface_test_behav/webtalk/usage_statistics_ext_xsim.html -wdm Z:/EE26/floatin_point_multiplier/floatin_point_multiplier.sim/sim_1/behav/xsim/xsim.dir/interface_test_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
