# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/bholen01/Downloads/nexys4ddrvgamouseoverlay1/Nexys4DDRVGAMouseOverlay/Nexys4DDRVGAMouseOverlay.cache/wt [current_project]
set_property parent.project_path C:/Users/bholen01/Downloads/nexys4ddrvgamouseoverlay1/Nexys4DDRVGAMouseOverlay/Nexys4DDRVGAMouseOverlay.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_cache_permissions disable [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/bholen01/Downloads/nexys4ddrvgamouseoverlay1/Nexys4DDRVGAMouseOverlay/Nexys4DDRVGAMouseOverlay.srcs/sources_1/imports/Basys3_Basic_Demo_1/clk_wiz_0_clk_wiz.vhd
  C:/Users/bholen01/Downloads/nexys4ddrvgamouseoverlay1/Nexys4DDRVGAMouseOverlay/Nexys4DDRVGAMouseOverlay.srcs/sources_1/imports/Basys3_Basic_Demo_1/Ps2Interface.vhd
  C:/Users/bholen01/Downloads/nexys4ddrvgamouseoverlay1/Nexys4DDRVGAMouseOverlay/Nexys4DDRVGAMouseOverlay.srcs/sources_1/imports/Basys3_Basic_Demo_1/MouseDisplay.vhd
  C:/Users/bholen01/Downloads/nexys4ddrvgamouseoverlay1/Nexys4DDRVGAMouseOverlay/Nexys4DDRVGAMouseOverlay.srcs/sources_1/imports/Basys3_Basic_Demo_1/clk_wiz_0.vhd
  C:/Users/bholen01/Downloads/nexys4ddrvgamouseoverlay1/Nexys4DDRVGAMouseOverlay/Nexys4DDRVGAMouseOverlay.srcs/sources_1/imports/Basys3_Basic_Demo_1/MouseCtl.vhd
  C:/Users/bholen01/Downloads/nexys4ddrvgamouseoverlay1/Nexys4DDRVGAMouseOverlay/Nexys4DDRVGAMouseOverlay.srcs/sources_1/imports/Basys3_Basic_Demo_1/vga_ctrl.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/bholen01/Downloads/nexys4ddrvgamouseoverlay1/Nexys4DDRVGAMouseOverlay/Nexys4DDRVGAMouseOverlay.srcs/constrs_1/imports/XDC/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files C:/Users/bholen01/Downloads/nexys4ddrvgamouseoverlay1/Nexys4DDRVGAMouseOverlay/Nexys4DDRVGAMouseOverlay.srcs/constrs_1/imports/XDC/Nexys4DDR_Master.xdc]


synth_design -top vga_ctrl -part xc7a100tcsg324-1


write_checkpoint -force -noxdef vga_ctrl.dcp

catch { report_utilization -file vga_ctrl_utilization_synth.rpt -pb vga_ctrl_utilization_synth.pb }
