# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir Z:/EE26/butterfly_unit/butterfly_unit.cache/wt [current_project]
set_property parent.project_path Z:/EE26/butterfly_unit/butterfly_unit.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo z:/EE26/butterfly_unit/butterfly_unit.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files Z:/EE26/butterfly_unit/rominit_butterfly.coe
add_files -quiet Z:/EE26/butterfly_unit/butterfly_unit.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.dcp
set_property used_in_implementation false [get_files Z:/EE26/butterfly_unit/butterfly_unit.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.dcp]
read_vhdl -library xil_defaultlib {
  Z:/EE26/butterfly_unit/butterfly_unit.srcs/sources_1/new/complex.vhd
  Z:/EE26/butterfly_unit/butterfly_unit.srcs/sources_1/new/butterfly_unit.vhd
  Z:/EE26/butterfly_unit/butterfly_unit.srcs/sources_1/new/fft_8point_3stage.vhd
  Z:/EE26/butterfly_unit/butterfly_unit.srcs/sources_1/new/fft_wrapper.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc Z:/EE26/butterfly_unit/butterfly_unit.srcs/constrs_1/new/pinout.xdc
set_property used_in_implementation false [get_files Z:/EE26/butterfly_unit/butterfly_unit.srcs/constrs_1/new/pinout.xdc]


synth_design -top fft_wrapper -part xc7a100tcsg324-1


write_checkpoint -force -noxdef fft_wrapper.dcp

catch { report_utilization -file fft_wrapper_utilization_synth.rpt -pb fft_wrapper_utilization_synth.pb }
